### ISSUE TITLE
Make webpage responsive for large screens 

### ISSUE THREAD

**Issue by ajz003** [ajz003/Summon-Simulator#1]
Currently, the page looks fine on mobile devices, but is not for landscape views or larger screens (tablets, PC monitors, etc.) Feel free to try and make it good!

The HTML file in use is wireframe.html. I will move all the HTML stuff to index.html once everything is done. Everything should be done via Bootstrap.

**Comment by PranjalSrivastava092** [comment]
I'll try this

**Comment by PranjalSrivastava092** [comment]
Issued a Pull Request.. hope it solves your issue
